version: "3.3"
services:
  server:
    restart: unless-stopped
    build:
        context: .
        args:
            GOARCH: arm64
            GOOS: linux
    environment:
        CONFIG: ./config.json
    volumes: 
        # mounts the private-key/secret
        - /etc/letsencrypt/archive/domain.com/privkey1.pem:/app/key.pem
        # mounts the public-key/certificate
        - /etc/letsencrypt/archive/domain.com/cert1.pem:/app/certificate.pem
        # mounts the config file
        - ./config.json:/app/config.json
        # mounts the directory from where to serves files from
        - ./public:/app/public
    ports:
        - 10443:443
